[build]
  command = "npm install -g @aws-amplify/cli && sh headless_amplify_pull.sh && npm run build"
  functions = "public/functions"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"